#!/bin/sh
#~ItzSelenux

echo m=$2 > /tmp/nman
source /tmp/nman

help()
{
   printf "NeoMan is a program that get Man Pages from web
Options: 
    arch
    -a  Search on Arch Linux ManPages
    deb
    -d  Search on Debian ManPages
    fbsd
    -f  Search on FreeBSD ManPages
    void
    -v  Search on Void Linux ManPages

"
}
arch()
{
curl -s https://man.archlinux.org/man/$m.1 | sed 's/<\/*[^>]*>//g' | sed '1,57d' | head -n -69
curl -s https://man.archlinux.org/man/$m.2 | sed 's/<\/*[^>]*>//g' | sed '1,57d' | head -n -69
curl -s https://man.archlinux.org/man/$m.3 | sed 's/<\/*[^>]*>//g' | sed '1,57d' | head -n -69
curl -s https://man.archlinux.org/man/$m.4 | sed 's/<\/*[^>]*>//g' | sed '1,57d' | head -n -69
curl -s https://man.archlinux.org/man/$m.5 | sed 's/<\/*[^>]*>//g' | sed '1,57d' | head -n -69
curl -s https://man.archlinux.org/man/$m.6 | sed 's/<\/*[^>]*>//g' | sed '1,57d' | head -n -69
curl -s https://man.archlinux.org/man/$m.7 | sed 's/<\/*[^>]*>//g' | sed '1,57d' | head -n -69
curl -s https://man.archlinux.org/man/$m.8 | sed 's/<\/*[^>]*>//g' | sed '1,57d' | head -n -69
curl -s https://man.archlinux.org/man/$m.9 | sed 's/<\/*[^>]*>//g' | sed '1,57d' | head -n -69
}
deb()
{
curl -s https://manpages.debian.org/bullseye/$m/$m.1.en.html | sed 's/<\/*[^>]*>//g' | sed '1,877d' | head -n -52
curl -s https://manpages.debian.org/bullseye/$m/$m.2.en.html | sed 's/<\/*[^>]*>//g' | sed '1,877d' | head -n -52
curl -s https://manpages.debian.org/bullseye/$m/$m.3.en.html | sed 's/<\/*[^>]*>//g' | sed '1,877d' | head -n -52
curl -s https://manpages.debian.org/bullseye/$m/$m.4.en.html | sed 's/<\/*[^>]*>//g' | sed '1,877d' | head -n -52
curl -s https://manpages.debian.org/bullseye/$m/$m.5.en.html | sed 's/<\/*[^>]*>//g' | sed '1,877d' | head -n -52
curl -s https://manpages.debian.org/bullseye/$m/$m.6.en.html | sed 's/<\/*[^>]*>//g' | sed '1,877d' | head -n -52
curl -s https://manpages.debian.org/bullseye/$m/$m.7.en.html | sed 's/<\/*[^>]*>//g' | sed '1,877d' | head -n -52
curl -s https://manpages.debian.org/bullseye/$m/$m.8.en.html | sed 's/<\/*[^>]*>//g' | sed '1,877d' | head -n -52
curl -s https://manpages.debian.org/bullseye/$m/$m.9.en.html | sed 's/<\/*[^>]*>//g' | sed '1,877d' | head -n -52
}
void()
{ 
curl -s https://man.voidlinux.org/$m | sed 's/<\/*[^>]*>//g' | sed '1,99d' | head -n -10
}
fbsd()
{ 
curl -s https://www.freebsd.org/cgi/man.cgi?query=$m\&manpath=FreeBSD+13.1-RELEASE+and+Ports | sed 's/<\/*[^>]*>//g' | sed '1,631d' | head -n -29
}

case "${1}" in
   arch)
      arch;;
			deb)
      deb;;
   fbsd)
      fbsd;;
   void)
      void;;
   help)
      help;;
esac

while getopts ":adfv" option; do
   case $option in
      a) 
         arch
         exit;;
      d) 
         deb
         exit;;
      f)
         fbsd
         exit;;
      v)
         void
         exit;;
      h)
         help
         exit;;
esac done
